### ISSUE TITLE
🛑 Blog is down

### ISSUE THREAD

**Issue by itsnicecraft-actions** [ItsNiceCraft/status#2]
In [`488b315`](https://github.com/ItsNiceCraft/status/commit/488b315913eb6829fe0cde906645728203f300b7
), Blog (https://itsnicecraft.is-a.dev) was **down**:
- HTTP code: 404
- Response time: 169 ms

**Comment by ItsNiceCraft** [comment]
Downtime due to move to itsnicecraft.ovh (from itsnicecraft.is-a.dev)
